# Generated by Django 3.2.12 on 2024-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_customuser_type_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_transaction',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_transaction',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='type_transaction',
        ),
        migrations.AddField(
            model_name='customuser',
            name='niveau',
            field=models.CharField(blank=True, choices=[('6e', '6eme'), ('5e', '5eme'), ('4e', '4eme'), ('3e', '3eme'), ('2nd', '2nd'), ('1ere', '1ere'), ('Tle', 'Tle')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
