# Generated by Django 3.2.12 on 2024-05-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_auto_20240531_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tel',
            new_name='telephone',
        ),
    ]
