# Generated by Django 3.2.12 on 2024-06-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_customuser_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
