# Generated by Django 3.2.12 on 2024-06-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_customuser_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ID_transaction',
            field=models.CharField(default=0, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_transaction',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
