# Generated by Django 3.2.12 on 2024-06-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_auto_20240619_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_transaction',
            field=models.DateField(),
        ),
    ]
