# Generated by Django 3.2.12 on 2024-06-19 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_customuser_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_transaction',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
