# Generated by Django 3.2.12 on 2024-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_alter_customuser_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_transaction',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
