# Generated by Django 3.2.12 on 2024-07-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0003_remove_prof_niveau'),
        ('authentification', '0013_alter_customuser_date_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prof', models.CharField(default='', max_length=20)),
                ('prenom', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('matricule', models.CharField(default='000000', max_length=30)),
                ('numero', models.CharField(default='000000', max_length=13)),
                ('choix', models.IntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.matiere')),
            ],
        ),
    ]
