# Generated by Django 3.2.12 on 2024-07-03 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0004_auto_20240703_2331'),
        ('authentification', '0014_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prof',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentification_profs', to='gestion_cours.matiere'),
        ),
    ]
