# Generated by Django 3.2.12 on 2024-07-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_auto_20240703_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ID_transaction',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
