# Generated by Django 3.2.12 on 2024-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_alter_customuser_id_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ID_transaction',
            field=models.CharField(default=0, max_length=25, unique=True),
        ),
    ]
