# Generated by Django 3.2.12 on 2024-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0018_delete_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='est_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prof_matricule',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
