# Generated by Django 3.2.12 on 2024-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
        migrations.AddField(
            model_name='prof',
            name='choix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prof',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prof',
            name='matricule',
            field=models.CharField(default='000000', max_length=30),
        ),
        migrations.AddField(
            model_name='prof',
            name='niveau',
            field=models.CharField(blank=True, choices=[('math', 'mathematique'), ('svt', 'science de le vie et de la terre'), ('H-G', 'histoire geographie'), ('FR', 'francais'), ('ANG', 'anglais'), ('P-C', 'PHYSIQUE-CHIME'), ('PHILO', 'philosophie'), ('EPS', 'Education PHYSIQUE et SPORTIVE')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='numero',
            field=models.CharField(default='000000', max_length=13),
        ),
        migrations.AddField(
            model_name='prof',
            name='prenom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prof',
            name='nom_prof',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClasseMatiere',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
