# Generated by Django 3.2.12 on 2024-07-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_prof'),
        ('gestion_cours', '0003_remove_prof_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='authentification.prof'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='authentification.prof'),
        ),
        migrations.AlterField(
            model_name='profclasse',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.prof'),
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
