# Generated by Django 3.2.12 on 2024-07-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_auto_20240704_1314'),
        ('gestion_cours', '0004_auto_20240703_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='matieres',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='chapitre',
        ),
        migrations.AlterUniqueTogether(
            name='profclasse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profclasse',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='profclasse',
            name='prof',
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='ProfClasse',
        ),
    ]
