# Generated by Django 3.2.12 on 2024-07-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_cours', '0005_auto_20240704_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chapitre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_exercice', models.CharField(max_length=255)),
                ('chapitre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercice', to='gestion_cours.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=255)),
                ('cours_lien', models.URLField()),
                ('type_cours', models.CharField(blank=True, choices=[('pdf', 'text'), ('mp3', 'video'), ('jpeg', 'image')], max_length=10, null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='gestion_cours.chapitre')),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='gestion_cours.matiere'),
        ),
    ]
