# Generated by Django 3.2.12 on 2024-07-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='email_prof',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
