# Generated by Django 3.2.12 on 2024-07-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0007_cours_email_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='nom_matiere',
            field=models.CharField(blank=True, choices=[('MATHEMATIQUE', 'text'), ('PHYSIQUE-CHIMIE', 'video'), ('SVT', 'image'), ('ANGLAIS', 'image'), ('PHILOSOPHIE', 'image'), ('FRANCAIS', 'image'), ('ALLEMEND', 'image'), ('HISTOIRE-GEOGRAPHIE', 'image'), ('EPS', 'image')], max_length=20, null=True),
        ),
    ]
