# Generated by Django 3.2.12 on 2024-07-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0009_auto_20240707_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.niveau'),
        ),
    ]
