# Generated by Django 3.2.12 on 2024-07-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0010_alter_matiere_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.matiere'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.chapitre'),
        ),
    ]
