# Generated by Django 3.2.12 on 2024-07-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0011_auto_20240707_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='nom_chapitre',
            new_name='nom',
        ),
    ]
