# Generated by Django 3.2.12 on 2024-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0012_rename_nom_chapitre_chapitre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.CharField(blank=True, choices=[('6e', '6eme'), ('5e', '5eme'), ('4e', '4eme'), ('3e', '3eme'), ('2nd', '2nd'), ('1ere', '1ere'), ('Tle', 'Tle')], max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
    ]
