# Generated by Django 3.2.12 on 2024-07-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0013_auto_20240707_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='nom_matiere',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='niveau',
            field=models.CharField(blank=True, choices=[('MATHEMATIQUE', '6eme'), ('PHYSIQUE-CHIMIE', '5eme'), ('HISTOIRE-GEOGRAPHIE', '4eme'), ('ANGLAIS', '3eme'), ('PHILOSOPHIE', '2nd'), ('ALLEMAND', '1ere'), ('SVT', 'Tle')], max_length=20, null=True),
        ),
    ]
