# Generated by Django 3.2.12 on 2024-07-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0015_auto_20240707_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='matiere',
            field=models.CharField(blank=True, choices=[('MATHEMATIQUE', 'MATHEMATIQUE'), ('PHYSIQUE-CHIMIE', 'PHYSIQUE-CHIMIE'), ('HISTOIRE-GEOGRAPHIE', 'HISTOIRE-GEOGRAPHIE'), ('ANGLAIS', 'ANGLAIS'), ('PHILOSOPHIE', 'PHILOSOPHIE'), ('ALLEMAND', 'ALLEMAND'), ('SVT', 'SVT')], max_length=20, null=True),
        ),
    ]
