# Generated by Django 3.2.12 on 2024-07-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0016_alter_chapitre_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='nom',
            new_name='nom_chapitre',
        ),
    ]
