# Generated by Django 3.2.12 on 2024-07-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0017_rename_nom_chapitre_nom_chapitre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='nom_chapitre',
            new_name='nom',
        ),
    ]
