# Generated by Django 3.2.12 on 2024-07-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0020_auto_20240708_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='ID_chap',
        ),
    ]
