# Generated by Django 3.2.12 on 2024-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0021_remove_cours_id_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='creator_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
