# Generated by Django 3.2.12 on 2024-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0022_cours_creator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='cours_types',
            field=models.CharField(blank=True, choices=[('.pdf', 'texte'), ('.mp4', 'video')], max_length=4, null=True),
        ),
    ]
