# Generated by Django 3.2.12 on 2024-07-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0023_alter_cours_cours_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='cours_types',
            field=models.CharField(blank=True, choices=[('.pdf', 'texte'), ('.mp4', 'video'), ('.jpeg', 'image')], max_length=5, null=True),
        ),
    ]
