# Generated by Django 3.2.12 on 2024-07-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0025_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Cours',
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=255)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.cours')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='exercice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.exercice'),
        ),
    ]
