# Generated by Django 3.2.12 on 2024-07-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0026_auto_20240713_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exercice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.exercice'),
        ),
    ]
