# Generated by Django 3.2.12 on 2024-07-13 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0027_alter_question_exercice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.cours'),
        ),
    ]
