# Generated by Django 3.2.12 on 2024-07-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0028_alter_exercice_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
